export enum ProductInsertTestIdEnum {
    PRODUCT_INSERT_CONTAINER = "PRODUCT_INSERT_CONTAINER",
    PRODUCT_INSERT_INPUT_NAME = "PRODUCT_INSERT_INPUT_NAME",
    PRODUCT_INSERT_INPUT_IMAGE = "PRODUCT_INSERT_INPUT_IMAGE",
    PRODUCT_INSERT_INPUT_PRICE = "PRODUCT_INSERT_INPUT_PRICE",
    PRODUCT_INSERT_INPUT_SELECT = "PRODUCT_INSERT_INPUT_SELECT",
    PRODUCT_INSERT_BUTTON_CANCEL = "PRODUCT_INSERT_BUTTON_CANCEL",
    PRODUCT_INSERT_BUTTON_INSERT = "PRODUCT_INSERT_BUTTON_INSERT",


}